name: WWW-Blog-Metadata
version: 0.02
abstract: Extract common metadata from a weblog
author: Benjamin Trott <ben+cpan@stupidfool.org>
license: perl
distribution_type: module
requires:
  Class::ErrorHandler: 0
  HTML::Parser: 0
  Feed::Find: 0
  URI::Fetch: 0
  Class::Accessor: 0
  Module::Pluggable::Ordered: 0
no_index:
  directory:
    - t
    - inc
generated_by: Module::Install version 0.36
